- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0  # Use the sha / tag you want to point at
  hooks:
    - id: yapf

#- repo: local
#  hooks:
#    - id: tests
#      name: run tests
#      entry: tox
#      language: system
#      types: [python]
#      stages: [push]