dist: xenial   # required for Python >= 3.7
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  # PyPy versions
  - "pypy3"

install:
  - pip install poetry tox-travis
  - poetry install

script: tox

after_success: coveralls
