# for https://mybinder.org
# from https://github.com/binder-examples/python-conda_pip/blob/master/environment.yml
name: routingpy-examples
channels:
  - conda-forge
dependencies:
  - python
  - folium
  - pandas
  - shapely
  - colour
  - pip:
    - routingpy