name: tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python_version: [
            3.7,
            3.8,
            3.9,
            '3.10',
            pypy3
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        pip install -r requirements_dev.txt
    - name: style & lint checks
      run: |
        pre-commit run --all-files
    - name: pytest
      run: |
        coverage run --source=routingpy --module pytest
    - name: coveralls
      run: |
        coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}